spring.application.name=CloudProject

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.team-name=${TEAM_NAME}

cloud.aws.s3.bucket=${S3_BUCKET_NAME}
cloud.aws.region=${AWS_REGION}
cloud.aws.cloudfront.domain=${CLOUDFRONT_DOMAIN}