spring.application.name=CloudProject

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloud.aws.s3.bucket=cloudproject-hglfjeklsd-files-331608077829-ap-northeast-2-an
cloud.aws.region=ap-northeast-2