spring.application.name=CloudProject

server.port=8080

logging.level.root = INFO

management.endpoints.web.exposure.include=health

spring.servlet.multipart.max-file-size=10MB

cloud.aws.s3.bucket=${S3_BUCKET_NAME}
cloud.aws.region=${AWS_REGION}